/**
 * Authentication specification
 * Authentication specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user';


export interface AuthenticationResponseDto { 
    user?: UserDto;
    accessToken?: string;
    accessTokenDuration?: number;
    refreshToken?: string;
    refreshTokenDuration?: number;
}

