/**
 * Plantation specification
 * Plantation specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AreaDto } from './area';


export interface PlantationDto { 
    id?: number;
    name?: string;
    nip?: string;
    regon?: string;
    city?: string;
    street?: string;
    houseNumber?: number;
    flatNumber?: number;
    postCode?: string;
    area?: AreaDto;
    sectors?: Array<AreaDto>;
    ownerId?: number;
    employeeIds?: Array<number>;
}

