openapi: 3.0.3
info:
  title: UserStats specification
  description: UserStats specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /user-stats/report-collected:
    description: |
      Endpoint for reporting collected container with fruits
    post:
      tags:
        - "UserStats"
      operationId: reportCollected
      parameters:
        - name: userId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: harvestId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return OK status.
  /user-stats/get-stats-by-harvest:
    description: |
      Endpoint for getting stats object by specific harvest and specific user
    post:
      tags:
        - "UserStats"
      operationId: getStatsByHarvest
      parameters:
        - name: harvestId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
        - name: userId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok. Successful response will return OK status and stats object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserStats"
  /user-stats/get-stats-by-user:
    description: |
      Endpoint for getting list of stats by given user.
    post:
      tags:
        - "UserStats"
      operationId: getStatsByUser
      parameters:
        - name: userId
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PageRequest"
      responses:
        "200":
          description: Ok. Successful response will return OK status and paged stats.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedStats"
components:
  schemas:
    PageRequest:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        sortDirection:
          type: string
        sortColumn:
          type: string
    UserStats:
      type: object
      properties:
        id:
          type: integer
          format: int64
        collectedContainers:
          type: integer
          format: int64
        harvestId:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
    PagedStats:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/UserStats"
        page:
          $ref: "#/components/schemas/Page"
    Page:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer
