/**
 * Harvests specification
 * Harvests specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserHarvestDto { 
    id?: number;
    plantId?: number;
    row?: number;
    harvestStart?: string;
    harvestEnd?: string;
    harvestId?: number;
    userId?: number;
    sectorId?: number;
    plantationId?: number;
}

